# [START cloudbuild_yarn_node]
steps:
# Install dependencies
- name: node
  entrypoint: yarn
  args: ['install']
  dir: "docs"
# Run custom commands
- name: node
  entrypoint: yarn
  args: ['run', 'build']
  dir: "docs"
# [END cloudbuild_yarn_node]
